version: 2

references:
  executor_config: &executor_config
    docker:
      - image: circleci/node:10.16

jobs:
  setup:
    <<: *executor_config
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run: npm install --ignore-scripts
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *executor_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: npm test
  docs-build:
    <<: *executor_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run storybook-dist
      - persist_to_workspace:
          root: .
          paths:
            - storybook-dist
  docs-deploy:
    <<: *executor_config
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install and configure gh-pages
          command: |
            npm i -g gh-pages@2.0.1
            git config user.email "ci-build@aleth.io"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "02:a8:57:e9:40:17:39:fd:95:b1:ab:20:77:fc:7d:ce"
      - run:
          name: Deploy with gh-pages
          command: gh-pages -d storybook-dist -m 'gh deploy [ci skip]'
workflows:
  version: 2
  build:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - docs-build:
          requires:
            - setup
      - docs-deploy:
          requires:
            - build
            - docs-build
          branches:
            only:
              - master
              # TODO removeme
              - storybook
